package com.me.ifly6;

import java.io.*;

import javax.swing.text.DefaultCaret;

public class Addons extends Console {

	private static final long serialVersionUID = 1L;
	static Runtime rt = Runtime.getRuntime();
	static String userName = System.getProperty("user.name");
	private static final String IUTILITIES_DIR = "/Users/" + userName + "/Library/Application Support/iUtilities";

	public static void save(String[] args) throws IOException {
		log.append("\nOutput Saving System Invoked.");
		String report = output.getText();
		long time = System.currentTimeMillis();
		File f = new File(IUTILITIES_DIR);
		f.mkdirs();
		Writer output = null;
		File file = new File("/Users/" + userName + "/Library/Application Support/iUtilities/report" + time + ".txt");
		output = new BufferedWriter(new FileWriter(file));
		output.write(report);
		output.close();
		output.append("Contents Exported.");
	}
	public static void script() {
		output.append("\n** Checking ~/Library/Application Support/iUtilities/script/check.txt");
		// Some stuff.
	}
	public static void mindterm() throws IOException {
		File folder = new File("/Users/" + userName + "/Library/Application Support/iUtilities/");
		folder.mkdirs();
		String[] url = { "curl", "-o", "/Users/" + userName + 
				"/Library/Application Support/iUtilities/mindterm.jar", "http://ifly6server.no-ip.org/Public/mindterm.jar" };
		rt.exec(url);
		log.append("\nMindterm Download Invoked.");
		output.append("\nMindterm Downloaded to: " + IUTILITIES_DIR);
	}

	public static void purge(String[] args) throws IOException {
		log.append("\nInactive Memory Purged");
		output.append("\n" + computername + "~ $ purge");
		log.append("\nMindterm Download Invoked.");
		output.append("\nMindterm Downloaded to: " + IUTILITIES_DIR + "\nThis is a full Java Based SSH/Telnet Client, capable of using SSH -D." +
				"\nIt is however, not made by the iUtilities Team, and therefore, does not fall under our perview.");
	}
	public static void debug(String[] args) throws IOException {
		log.append("\niUtilities Debug Readout Command Executed");
		String debug = log.getText();
		long time = System.currentTimeMillis();
		File f = new File(IUTILITIES_DIR);
		f.mkdirs();
		Writer output = null;
		File file = new File(IUTILITIES_DIR + "/report" + time + ".txt");
		output = new BufferedWriter(new FileWriter(file));
		output.write(debug);
		output.close();
		output.append("\nDebug Contents Exported to File in: " + IUTILITIES_DIR);
	}
	public static void info(String[] args) throws InterruptedException, IOException{
		log.append("\nSystem Readout Invoked.");
		output.setText(null);
		output.append("Generated By: " + Info.version + " '" + Info.password + "' \n");
		output.append(" -- Current Running Processes -- \n");
		String[] com = { "ps", "ax" };
		String[] com1 = { "ifconfig" };
		Process proc = rt.exec(com);
		Process proc1 = rt.exec(com1);

		InputStream stderr = proc.getInputStream();
		InputStreamReader isr = new InputStreamReader(stderr);
		BufferedReader br = new BufferedReader(isr);
		String line = null;
		while ((line = br.readLine()) != null) {
			output.append(line + "\n"); }

		InputStream stderr1 = proc1.getInputStream();
		InputStreamReader isr1 = new InputStreamReader(stderr1);
		BufferedReader br1 = new BufferedReader(isr1);
		String line1 = null;
		output.append("\n -- Internet Information -- \n");
		while ((line1 = br1.readLine()) != null) {
			output.append(" " + line1 + "\n");
		}
		
		// Hardware
		output.append("\nAvailable cores: " + 
				Runtime.getRuntime().availableProcessors());
		output.append("\nFree memory (bytes): " + 
				Runtime.getRuntime().freeMemory());
		long maxMemory = Runtime.getRuntime().maxMemory();
		output.append("\nMax. memory (bytes): " + (Long.valueOf(maxMemory)));
		output.append("\nTotal memory (bytes): " + 
				Runtime.getRuntime().totalMemory());
		File[] roots = File.listRoots();
		output.append("\n");
		for (File root : roots) {
			output.append("\nFile system root: " + root.getAbsolutePath());
			output.append("\nFS Capacity (bytes): " + root.getTotalSpace());
			output.append("\nFS Free (bytes): " + root.getFreeSpace());
			output.append("\nFS Usable (bytes): " + root.getUsableSpace());
		}
		output.append("\n");
		output.append("\n" + System.getProperty("java.runtime.name") + " version " + System.getProperty("java.runtime.version") + System.getProperty("java.vm.version") + " by " + System.getProperty("java.vm.vendor"));
		output.append("\nExecution Directory: " + System.getProperty("user.dir"));
		output.append("\n");
		String nameOS = "os.name";
		String versionOS = "os.version";
		output.append("\nOperating System: " + System.getProperty(nameOS) + " " + System.getProperty(versionOS));
		output.append("\nUser: " + System.getProperty("user.name") + " ... with Home at: " + System.getProperty("user.home"));
		output.append("\nDesktop: " + System.getProperty("sun.desktop"));
	}
	public static void defaultCarat(Object object) {
		DefaultCaret caret = (DefaultCaret)output.getCaret();
		caret.setUpdatePolicy(2);
	}
	public static void delete(String[] args) throws IOException {
		log.append("\niUtilities Folder Deletion Commencing.");
		String[] delete = {"rm","-rf","'~/Library/Application Support/iUtilities'"};
		ProcessBuilder builder = new ProcessBuilder(delete);
		builder.start();
	}
}
